### ISSUE TITLE
Handling of chat permission updates causes voice chat to be unmuted

### ISSUE THREAD

**Issue by qloc-wgud** [PlayFab/PlayFabPartyUnity#27]
We encountered a scenario where voice connection to users becomes unmuted if player is not using voice chat by default. This seems to be caused by initial chat permission handling in the plugin code.

In PlayFabChatXboxLivePolicyProvider, handling of chat permission updates for a user in UpdateChatPermissionInfoComplete function, causes instant application of updated rules to the voice chat connection - even if they are less restrictive than currently set.

It would be good if we had a callback fired in this place instead of a forced update.
Keeping most restrictive options between the currently set ones and the new ones would also be an improvement.

We are using plugin version 1.7.0.0-main.0

**Comment by nassosterz-ms** [comment]
We cannot have a callback instead of a forced update in PlayFabChatXboxLivePolicyProvider::UpdateChatPermissionInfoComplete  since it could result in violation of XR policies.

Regarding the most restrictive options, that issue has been discussed and will probably be included in the next release.

Thank you again for bringing this to our attention.
